name: FUT Infrastructure IG Publisher image build

on:
  workflow_dispatch: # Enable manual run on main
    branches:
      - main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  DATE_TAG: "$(date +'%Y-%m-%d')"

jobs:
  container:
    name: Container build & push
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: aevea/action-kaniko@v0.13.0
        with:
          registry: ${{ env.REGISTRY }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ig-publisher
          tag_with_latest: true
          tag: ${{ env.DATE_TAG }}
