name: FUT Infrastructure IG Publisher image build

on:
  workflow_dispatch: # Enable manual run on main
    branches: [ main ]
  push:
    tags: ['*']

env:
  REGISTRY: ghcr.io
  DATE_TAG: "$(date +'%Y-%m-%d')"

jobs:
  container:
    name: Container build & push
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build
        uses: aevea/action-kaniko@v0.13.0
        with:
          registry: ${{ env.REGISTRY }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ig-publisher
          tag_with_latest: ${{ github.ref_type == 'tag' && 'true' || 'false' }}
          tag: ${{ github.ref_type == 'tag' && github.ref_name || env.DATE_TAG }}
          extra_args: ${{ github.ref_type == 'tag' && format('--build-arg IG_PUB_VERSION={0}', github.ref_name) || '' }}
